# Generated by Django 5.1 on 2024-09-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('education', models.CharField(max_length=100)),
                ('MMSE', models.IntegerField(default=0)),
                ('MoCA', models.IntegerField(default=0)),
                ('has_depression', models.BooleanField(default=False)),
                ('has_anxiety', models.BooleanField(default=False)),
            ],
        ),
    ]
