# Generated by Django 5.1 on 2024-09-21 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_game_move_person_delete_patient_game_personid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiomarkerType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Biomarker',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.biomarkertype')),
            ],
        ),
    ]
