# Generated by Django 5.1 on 2024-09-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_biomarkerstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
