# Generated by Django 5.1 on 2024-09-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_game_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomarker',
            name='unit',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
