# Generated by Django 5.1 on 2024-09-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_biomarker_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='patient_code',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
