# Generated by Django 5.1 on 2024-09-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_person_mmse_person_moca'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='full_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
