# Generated by Django 5.1 on 2024-10-17 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_question_questionnaire_multiplechoiceoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='questionnaire',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.person')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.response'),
        ),
    ]
