# Generated by Django 5.1 on 2024-10-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_questionnaire_prolific_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='person',
        ),
    ]
