# Generated by Django 5.1 on 2024-10-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_questionnairesections_title_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairesections',
            name='title_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
