# Generated by Django 5.1 on 2024-10-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_questionnairesections_title_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='charLimit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='noSpecialChars',
            field=models.BooleanField(default=False),
        ),
    ]
