# Generated by Django 5.1 on 2024-10-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_alter_person_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='playlevel',
            field=models.CharField(choices=[('1', 'Dagelijks'), ('2', 'Wekelijks'), ('3', 'Maandelijks'), ('4', 'Jaarlijks'), ('5', 'Nooit')], db_column='playLevel', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='tabletlevel',
            field=models.CharField(choices=[('1', 'Dagelijks'), ('2', 'Wekelijks'), ('3', 'Maandelijks'), ('4', 'Jaarlijks'), ('5', 'Nooit')], db_column='tabletLevel', max_length=1),
        ),
    ]
