# Generated by Django 5.1 on 2024-10-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_alter_person_playlevel_alter_person_tabletlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=45)),
                ('model_F1_score', models.FloatField()),
                ('true_positive', models.IntegerField()),
                ('false_positive', models.IntegerField()),
                ('true_negative', models.IntegerField()),
                ('false_negative', models.IntegerField()),
            ],
        ),
    ]
