# Generated by Django 5.1 on 2024-11-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_mlmodeldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomarker',
            name='low',
            field=models.CharField(choices=[('G', 'Good'), ('B', 'Bad')], default='G', max_length=2),
        ),
    ]
