# Generated by Django 5.1 on 2024-11-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_question_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
    ]
