# Generated by Django 5.1 on 2024-11-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomarker',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
