# Generated by Django 5.1 on 2024-11-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_biomarker_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ml_probability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
